### ISSUE TITLE
Charshes when someone talks

### ISSUE THREAD

**Issue by JonJon565** [Arny4/Afk-Bot#71]
when any play says something the bot crashes and i get this error

```
Hint: hit control+c anytime to enter REPL.
Listening on port 8000
[2023-03-13T04:05:40.662] [INFO] default - Bot joined to the server
/home/runner/Afk-Bot/node_modules/prismarine-chat/index.js:390
      const fstr = format.formatString
                          ^

TypeError: Cannot read properties of undefined (reading 'formatString')
    at ChatMessage.fromNetwork (/home/runner/Afk-Bot/node_modules/prismarine-chat/index.js:390:27)
    at Client.<anonymous> (/home/runner/Afk-Bot/node_modules/mineflayer/lib/plugins/chat.js:121:25)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at Client.<anonymous> (/home/runner/Afk-Bot/node_modules/minecraft-protocol/src/client/chat.js:197:14)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at FullPacketParser.<anonymous> (/home/runner/Afk-Bot/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:513:28)

Node.js v18.12.1
repl process died unexpectedly: exit status 1
 
(To exit

```

**Comment by urFate** [comment]
https://github.com/urFate/Afk-Bot/issues/67
